services:
  sit-aw-anchoring:
    build:
      context: .
      dockerfile: Dockerfile-jazzy
    image: sit-aw-anchoring:0.3.0-humble #ghcr.io/convince-project/sit-aw-anchoring:0.3.0-jazzy
    container_name: sit_aw_anchoring_030_jazzy_ctr