# version: 0.3.0
FROM ros:jazzy-ros-base

ENV ROS_DISTRO=jazzy

ARG DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

RUN chmod 1777 /tmp

ENV USERNAME=user

RUN addgroup "$USERNAME" \
 && adduser "$USERNAME" --gid 1000 --disabled-password \
 && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN apt update &&\
	apt install -y --no-install-recommends wget gedit python3-pip \
	  nlohmann-json3-dev ros-jazzy-rmw-cyclonedds-cpp

ENV XDG_RUNTIME_DIR=/tmp/runtime-root
RUN mkdir /usr/share/desktop-directories

RUN python3 -m pip install --break-system-packages --upgrade pip;	\
    pip3 install --break-system-packages pybullet

RUN curl -1sLf \
  'https://repo.typedb.com/public/public-release/setup.deb.sh' \
  | sudo -E bash

RUN apt update &&\
	apt install -y --no-install-recommends typedb=2.28.3

RUN apt update &&\
  wget -q -O /tmp/typedb-studio-linux-2.28.6-1.deb https://repo.typedb.com/public/public-release/raw/names/typedb-studio-linux-x86_64-deb/versions/2.28.6/typedb-studio-linux-x86_64-2.28.6.deb && apt install -y --no-install-recommends /tmp/typedb-studio-linux-2.28.6-1.deb && rm /tmp/typedb-studio-linux-2.28.6-1.deb

# Adjust executable name of typedb studio
RUN ln -s /opt/typedb-studio/bin/TypeDB\ Studio /opt/typedb-studio/bin/typedb-studio

RUN mkdir -p /home/"$USERNAME"/sit-aw-anchoring/colcon_ws
COPY ./src /home/"$USERNAME"/sit-aw-anchoring/colcon_ws/src
WORKDIR /home/"$USERNAME"/sit-aw-anchoring/colcon_ws

#Install missing dependencies (most of them should be tackeld above to optimise build time)
RUN source /opt/ros/jazzy/setup.bash &&\
	apt update &&\
	rosdep fix-permissions &&\
	rosdep update &&\
	rosdep install --from-paths src --ignore-src -r -y

#Build the components (separate step to cache the rosdep installs)
RUN source /opt/ros/jazzy/setup.bash &&\
	colcon build --symlink-install

#Set the .bashrc
COPY --chown="$USERNAME":"$USERNAME" ./bashrc /home/"$USERNAME"/.bashrc

#Set the typedb-studio connection
#For the root user (when connecting to the docker through exec)
COPY --chown="$USERNAME":"$USERNAME" ./typedb-studio.properties /root/.typedb-studio/properties/typedb-studio.properties
#For the user created when running the entrypoint
COPY --chown="$USERNAME":"$USERNAME" ./typedb-studio.properties /home/user/.typedb-studio/properties/typedb-studio.properties

#Set the entrypoint
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

#Move to workdir
RUN mkdir -p /home/"$USERNAME"/dev/colcon_ws
WORKDIR /home/"$USERNAME"/dev/colcon_ws

