// --------------------------------------------------------
// Copyright (c)
//
// contributions by author
//                  author@somewhere.net
// maintained by    maintainer
//                  maintainer@somewhere.net

// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#include "anchoring_process_def/anchoring_process_impl.h"

// declare options
rclcpp::NodeOptions anchoring_process_options;

int main(int argc, char **argv) {
  rclcpp::init(argc, argv);

  auto anchoring_process = std::make_shared < anchoring_process_def::anchoring_process_impl > (anchoring_process_options);

  RCLCPP_INFO(anchoring_process->get_logger(), "anchoring_process has been initialized");

  rclcpp::executors::MultiThreadedExecutor executor;

  executor.add_node(anchoring_process->get_node_base_interface());

  executor.spin();
  rclcpp::shutdown();
}

