// --------------------------------------------------------
// Copyright (c)
//
// contributions by author
//                  author@somewhere.net
// maintained by    maintainer
//                  maintainer@somewhere.net

// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ANCHORING_PROCESS_DEF_ANCHORING_PROCESS_H
#define ANCHORING_PROCESS_DEF_ANCHORING_PROCESS_H

/************************************************************
 anchoring_process class header
 ************************************************************/

#include "anchoring_process_def/Pkg_anchoring_process_def.h"

#include "rclcpp_lifecycle/lifecycle_node.hpp"

#include "anchoring_process_interfaces/action/set_ontology.hpp"
#include "anchoring_process_interfaces/action/populate_instances.hpp"
#include "anchoring_process_interfaces/action/update_state.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>
#include <rclcpp_action/rclcpp_action.hpp>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Service;
}
}
namespace ros2Library {
namespace rclcpp_action {
class Server;
}
}

namespace anchoring_process_def {

/************************************************************/
/**
 * 
 */
class anchoring_process: public rclcpp_lifecycle::LifecycleNode {

public:

  /**
   * 
   * @param options 
   */
  anchoring_process(rclcpp::NodeOptions /*in*/options);

  /**
   * 
   */
  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
  on_configure(const rclcpp_lifecycle::State &) override;

  /**
   * 
   */
  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
  on_activate(const rclcpp_lifecycle::State & state) override;

  /**
   * 
   */
  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
  on_deactivate(const rclcpp_lifecycle::State & state) override;

  /**
   * 
   */
  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
  on_cleanup(const rclcpp_lifecycle::State & state) override;

  /**
   * 
   */
  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
  on_shutdown(const rclcpp_lifecycle::State & state) override;

protected:

  /**
   * 
   */
  rclcpp::CallbackGroup::SharedPtr cbg_Activity01_;

  /**
   * 
   */
  rclcpp_action::Server<anchoring_process_interfaces::action::SetOntology>::SharedPtr set_ontology_actsrv_;

  /**
   * 
   */
  rclcpp_action::Server<anchoring_process_interfaces::action::PopulateInstances>::SharedPtr populate_instances_actsrv_;

  /**
   * 
   */
  rclcpp_action::Server<anchoring_process_interfaces::action::UpdateState>::SharedPtr update_state_actsrv_;

};

/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace anchoring_process_def

/************************************************************
 End of anchoring_process class header
 ************************************************************/

#endif
