// --------------------------------------------------------
// Copyright (c)
//
// contributions by author
//                  author@somewhere.net
// maintained by    maintainer
//                  maintainer@somewhere.net

// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define anchoring_process_def_anchoring_process_BODY

/************************************************************
 anchoring_process class body
 ************************************************************/

// include associated header file
#include "anchoring_process_def/anchoring_process.h"

#include <rclcpp/version.h>

// Derived includes directives
#include "anchoring_process_def/anchoring_process_impl.h"
#include "anchoring_process_def/anchoring_process_main.h"
#include "rclcpp/rclcpp.hpp"
#include "rclcpp_action/rclcpp_action.hpp"

namespace anchoring_process_def {

// Function to support both Rolling and Humble on the main branch
// Rolling has deprecated the version of the create_client method that takes
// rmw_qos_profile_services_default for the QoS argument
#if RCLCPP_VERSION_GTE(17, 0, 0)  // Rolling
auto qosDefault()
{
  return rclcpp::SystemDefaultsQoS();
}
#else  // Humble
auto qosDefault()
{
  return rmw_qos_profile_services_default;
}
#endif

// static attributes (if any)

/**
 * 
 * @param options 
 */
anchoring_process::anchoring_process(rclcpp::NodeOptions /*in*/options) :
    rclcpp_lifecycle::LifecycleNode("anchoring_process", options) {

  // Create callback group(s)
  cbg_Activity01_ = create_callback_group(
      rclcpp::CallbackGroupType::MutuallyExclusive);
  dt_client_cb_group_ = create_callback_group(
      rclcpp::CallbackGroupType::MutuallyExclusive);

  declare_parameter<std::vector<std::string>>("dt.service_names", std::vector<std::string>{});
  declare_parameter("dt.timeout", 2);
}

rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
  anchoring_process::on_configure(const rclcpp_lifecycle::State &)
{

    RCLCPP_INFO(get_logger(), "Configuring (base)");

    // dt-related parameters
    dt_service_names_ = get_parameter("dt.service_names").as_string_array();
    if (dt_service_names_.empty()) {
      RCLCPP_ERROR(get_logger(), "dt.service_names is empty!");
      return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::FAILURE;
    }
    dt_clients_.clear(); // Clear previous clients (important for lifecycle reconfigure)

    dt_timeout_ = get_parameter("dt.timeout").as_int();
    if (dt_timeout_ <= 0) {
      RCLCPP_WARN(
        get_logger(),
        "Parameter 'dt.timeout' is <= 0. Using default 2 seconds");
      dt_timeout_ = 2;
    }    

    // Create dt clients (one client per service)
    for (const auto & service_name : dt_service_names_) {
      if (service_name.empty()) {
        RCLCPP_ERROR(get_logger(), "Empty service name found!");
        return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::FAILURE;
      }
      auto client = this->create_client<std_srvs::srv::Trigger>(
          service_name,
          qosDefault(),
          dt_client_cb_group_
        );
      if (!client->wait_for_service(
          std::chrono::duration<int>(dt_timeout_))) {
        RCLCPP_ERROR(get_logger(), "DT service %s not available after timeout", service_name.c_str());
        return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::FAILURE;
      }
      dt_clients_.push_back(client);
    }

    // set_ontology action server
    set_ontology_actsrv_ =
      rclcpp_action::create_server <anchoring_process_interfaces::action::SetOntology> (
              this,
              "~/set_ontology",
              std::bind(
                &anchoring_process_def::anchoring_process_impl::set_ontology_goal,
                (anchoring_process_impl*) this,
                std::placeholders::_1,
                std::placeholders::_2
              ),
              std::bind(
                &anchoring_process_def::anchoring_process_impl::set_ontology_cancel,
                (anchoring_process_impl*) this,
                std::placeholders::_1
              ),
              std::bind(
                &anchoring_process_def::anchoring_process_impl::set_ontology_accepted,
                (anchoring_process_impl*) this,
                std::placeholders::_1
              ),
              rcl_action_server_get_default_options(),
              cbg_Activity01_
      );

    // populate_instances action server
    populate_instances_actsrv_ =
      rclcpp_action::create_server <anchoring_process_interfaces::action::PopulateInstances> (
              this,
              "~/populate_instances",
              std::bind(
                &anchoring_process_def::anchoring_process_impl::populate_instances_goal,
                (anchoring_process_impl*) this,
                std::placeholders::_1,
                std::placeholders::_2
              ),
              std::bind(
                &anchoring_process_def::anchoring_process_impl::populate_instances_cancel,
                (anchoring_process_impl*) this,
                std::placeholders::_1
              ),
              std::bind(
                &anchoring_process_def::anchoring_process_impl::populate_instances_accepted,
                (anchoring_process_impl*) this,
                std::placeholders::_1
              ),
              rcl_action_server_get_default_options(),
              cbg_Activity01_
      );

    // update_state action server
    update_state_actsrv_ =
      rclcpp_action::create_server <anchoring_process_interfaces::action::UpdateState> (
              this,
              "~/update_state",
              std::bind(
                &anchoring_process_def::anchoring_process_impl::update_state_goal,
                (anchoring_process_impl*) this,
                std::placeholders::_1,
                std::placeholders::_2
              ),
              std::bind(
                &anchoring_process_def::anchoring_process_impl::update_state_cancel,
                (anchoring_process_impl*) this,
                std::placeholders::_1
              ),
              std::bind(
                &anchoring_process_def::anchoring_process_impl::update_state_accepted,
                (anchoring_process_impl*) this,
                std::placeholders::_1
              ),
              rcl_action_server_get_default_options(),
              cbg_Activity01_
      );

  return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;
}

rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
  anchoring_process::on_activate(const rclcpp_lifecycle::State & state)
{
  (void)state;
  return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;
}

rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
  anchoring_process::on_deactivate(const rclcpp_lifecycle::State & state)
{
  (void)state;
  return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;
}

rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
  anchoring_process::on_cleanup(const rclcpp_lifecycle::State & state)
{
  (void)state;
  return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;
}

rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
  anchoring_process::on_shutdown(const rclcpp_lifecycle::State & state)
{
  (void)state;
  return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;
}

} // of namespace anchoring_process_def

/************************************************************
 End of anchoring_process class body
 ************************************************************/
